// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNxCpmYLYZ1qAnijGcEbT1mXVUyGwE_Pw',
    appId: '1:666009452734:web:e56972164b1e801b969eef',
    messagingSenderId: '666009452734',
    projectId: 'barber-app-3f8cb',
    authDomain: 'barber-app-3f8cb.firebaseapp.com',
    storageBucket: 'barber-app-3f8cb.firebasestorage.app',
    measurementId: 'G-75W1LS77SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs9Uky7FQYSx-dZONA5SwKFK_KhF8dOBQ',
    appId: '1:666009452734:android:10828d6ff841e7af969eef',
    messagingSenderId: '666009452734',
    projectId: 'barber-app-3f8cb',
    storageBucket: 'barber-app-3f8cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1grYB88AmMeYzPe7Hf5KfXA3_5xTZRz0',
    appId: '1:666009452734:ios:081547792f083e5b969eef',
    messagingSenderId: '666009452734',
    projectId: 'barber-app-3f8cb',
    storageBucket: 'barber-app-3f8cb.firebasestorage.app',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1grYB88AmMeYzPe7Hf5KfXA3_5xTZRz0',
    appId: '1:666009452734:ios:081547792f083e5b969eef',
    messagingSenderId: '666009452734',
    projectId: 'barber-app-3f8cb',
    storageBucket: 'barber-app-3f8cb.firebasestorage.app',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNxCpmYLYZ1qAnijGcEbT1mXVUyGwE_Pw',
    appId: '1:666009452734:web:b7f056a33156eac4969eef',
    messagingSenderId: '666009452734',
    projectId: 'barber-app-3f8cb',
    authDomain: 'barber-app-3f8cb.firebaseapp.com',
    storageBucket: 'barber-app-3f8cb.firebasestorage.app',
    measurementId: 'G-NTJ9Z1FCJF',
  );
}
